# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-24 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_marriage', models.DateField(blank=True, null=True)),
                ('date_of_divorce', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('mariage ou Pacs', 'mariage ou Pacs'), ('concubinage', 'concubinage'), ('divorce', 'divorce')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=False)),
                ('idi', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('F', 'femme'), ('H', 'homme'), ('A', 'autre')], max_length=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/img', verbose_name=models.CharField(max_length=50))),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('family_as_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_as_child', to='menu.Family')),
                ('family_as_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_as_parent', to='menu.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('church', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='place_of_birth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_of_birth', to='menu.Location'),
        ),
        migrations.AddField(
            model_name='individual',
            name='place_of_death',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_of_death', to='menu.Location'),
        ),
        migrations.AddField(
            model_name='individual',
            name='place_of_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Location'),
        ),
        migrations.AddField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(related_name='children_set', to='menu.Individual'),
        ),
        migrations.AddField(
            model_name='family',
            name='parent1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='father', to='menu.Individual'),
        ),
        migrations.AddField(
            model_name='family',
            name='parent2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother', to='menu.Individual'),
        ),
        migrations.AddField(
            model_name='family',
            name='place_of_marriage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_of_marriage', to='menu.Location'),
        ),
    ]
