# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-24 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='idi',
        ),
    ]
