# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_individual_idi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gedcom_id', models.CharField(max_length=10)),
                ('date_of_marriage', models.DateField(blank=True, null=True)),
                ('date_of_divorce', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('mariage ou Pacs', 'mariage ou Pacs'), ('concubinage', 'concubinage'), ('divorce', 'divorce')], max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='family',
            name='children',
        ),
        migrations.RemoveField(
            model_name='family',
            name='parent1',
        ),
        migrations.RemoveField(
            model_name='family',
            name='parent2',
        ),
        migrations.RemoveField(
            model_name='family',
            name='place_of_marriage',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='family_as_child',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='family_as_parent',
        ),
        migrations.AddField(
            model_name='individual',
            name='gedcom_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.AddField(
            model_name='relationship',
            name='parent1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person1', to='menu.Individual'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='parent2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person2', to='menu.Individual'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='place_of_marriage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_of_marriage', to='menu.Location'),
        ),
        migrations.AddField(
            model_name='child',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='menu.Individual'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='father', to='menu.Individual'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother', to='menu.Individual'),
        ),
    ]
