# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180625_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
