# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20180625_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='church',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
