# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20180625_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='father', to='menu.Individual'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother', to='menu.Individual'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'femme'), ('H', 'homme'), ('A', 'autre')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_of_birth', to='menu.Location'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='place_of_death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_of_death', to='menu.Location'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='place_of_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Location'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='place_of_marriage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_of_marriage', to='menu.Location'),
        ),
    ]
