# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20180626_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='first_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
