# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20180627_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
