# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20180628_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'femme'), ('M', 'homme'), ('A', 'autre')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('mariage ou Pacs', 'mariage ou Pacs'), ('concubinage', 'concubinage'), ('divorce', 'divorce')], max_length=16),
        ),
    ]
