# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-30 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20180629_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['parent1', 'parent2'], 'verbose_name_plural': 'Enfant'},
        ),
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['last_name', 'first_name', 'date_of_birth'], 'verbose_name_plural': 'Individu'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['country', 'city'], 'verbose_name_plural': 'Place'},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['parent1', 'parent2'], 'verbose_name_plural': 'Relation'},
        ),
        migrations.AlterField(
            model_name='child',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='menu.Individual'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father', to='menu.Individual'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother', to='menu.Individual'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_of_birth', to='menu.Location'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='place_of_death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_of_death', to='menu.Location'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='place_of_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Location'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='parent1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person1', to='menu.Individual'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='parent2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person2', to='menu.Individual'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='place_of_marriage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_of_marriage', to='menu.Location'),
        ),
    ]
