# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-01 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_auto_20180630_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['country', 'city', 'church'], 'verbose_name_plural': 'Place'},
        ),
        migrations.AlterField(
            model_name='individual',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/img', verbose_name='image'),
        ),
    ]
