# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20180701_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='is_deceased',
            field=models.BooleanField(default=False),
        ),
    ]
