# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_auto_20180716_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='first_name',
            field=models.CharField(blank=True, default='?', max_length=70),
        ),
        migrations.AlterField(
            model_name='individual',
            name='last_name',
            field=models.CharField(blank=True, default='?', max_length=30),
        ),
    ]
