# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-28 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('menu', '0020_modification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='subject',
        ),
        migrations.AddField(
            model_name='modification',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='modification',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
