# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-28 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_auto_20180728_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
