# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-28 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_auto_20180728_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='test',
            field=models.DateTimeField(null=True),
        ),
    ]
